// Generated by citadel-generate-app-metadata from package.json#citadel.

import type { AppManifest, AppPackageDescriptor } from '@citadel/platform/app';

export const generatedManifest = {
  appId: "snake",
  label: "Snake",
  defaultSpaceId: "general",
  persistence: "none",
  version: "0.1.0"
} satisfies AppManifest;

export const generatedAppPackage = {
  appId: generatedManifest.appId,
  manifest: generatedManifest,
  packageName: "@citadel/app-snake",
  client: {
    subpath: "./client",
    registrationExport: "snakeClientRegistration"
  },
  server: {
    subpath: "./server",
    registrationExport: "snakeServerRegistration"
  }
} satisfies AppPackageDescriptor;
