export {
  NAMESPACE_MAX_LENGTH,
  NAMESPACE_PATTERN,
  isNamespace,
  type AcceptNamespaceClientMessage,
  type AuthenticatedPrincipal,
  type AuthenticateMessage,
  type AuthenticationStateMessage,
  type ClaimNamespaceMessage,
  type ClientMessage,
  type ClientPacketMessage,
  type ClientState,
  type CloseNamespaceMessage,
  type ConnectionTarget,
  type NamespaceClaimedMessage,
  type NamespaceClientStateMessage,
  type NamespaceConnectMessage,
  type NamespaceDisconnectMessage,
  type OpenNamespaceMessage,
  type PublicPrincipal,
  type RejectNamespaceClientMessage,
  type RelayClientPacketMessage,
  type RelayErrorMessage,
  type RelayServerPacketMessage,
  type ReleaseNamespaceMessage,
  type RevokeNamespaceClientMessage,
  type ServerMessage,
  type ServerPacketMessage,
  type ServerPacketTarget
} from './shared.js';
export {
  AUTH_TOKEN_MAX_LENGTH,
  PRE_SHARED_KEY_BYTES,
  PRE_SHARED_KEY_ENCODED_LENGTH,
  PRINCIPAL_ID_MAX_LENGTH,
  createPreSharedKeyAuthenticator,
  parsePreSharedKeyConfig,
  validateAuthenticatedPrincipal,
  validatePreSharedKeyConfig,
  type AppOwnerConfig,
  type PreSharedKeyConfig,
  type RelayAuthenticator
} from './auth.js';
