export {
  DEFAULT_SPACE_ID,
  DISPLAY_NAME_MAX_LENGTH,
  GUEST_ID_MAX_LENGTH,
  GUEST_ID_PATTERN,
  NAMESPACE_MAX_LENGTH,
  NAMESPACE_PATTERN,
  SPACE_ID_MAX_LENGTH,
  SPACE_ID_PATTERN,
  isNamespace,
  normalizeGuestId,
  normalizeSpaceId,
  type AuthenticatedPrincipal,
  type AuthenticateMessage,
  type AuthenticationStateMessage,
  type ClientMessage,
  type ClaimNamespaceMessage,
  type ConnectionTarget,
  type JoinSpaceMessage,
  type LeaveSpaceMessage,
  type NamespaceClaimedMessage,
  type PacketTarget,
  type Participant,
  type ParticipantEvent,
  type PublicPrincipal,
  type ReleaseNamespaceMessage,
  type RelayErrorMessage,
  type RelayPacketMessage,
  type ServerMessage,
  type SpacePacketMessage,
  type SpaceStateMessage
} from './shared.js';
export {
  AUTH_TOKEN_MAX_LENGTH,
  PRE_SHARED_KEY_BYTES,
  PRE_SHARED_KEY_ENCODED_LENGTH,
  PRINCIPAL_ID_MAX_LENGTH,
  createPreSharedKeyAuthenticator,
  parsePreSharedKeyConfig,
  validateAuthenticatedPrincipal,
  validatePreSharedKeyConfig,
  type AppOwnerConfig,
  type PreSharedKeyConfig,
  type RelayAuthenticator
} from './auth.js';
export type { ValidationResult } from './validation.js';
