// Generated by scripts/generate-bundled-apps.mjs. Do not edit by hand.
import type { InstalledAppCatalogEntry } from '@citadel-platform/platform/app';



export const bundledInstalledApps = [

] satisfies InstalledAppCatalogEntry[];
