// Generated by scripts/generate-bundled-apps.mjs. Do not edit by hand.
import type { AppPackageDescriptor } from '@citadel/platform/app';
import type { ClientAppRegistration } from '@citadel/platform/client';
import type { ServerAppRegistration } from '@citadel/platform/server-app';
import { chatClientRegistration as bundledClientRegistration0 } from '@citadel/app-chat/client';
import { chessClientRegistration as bundledClientRegistration1 } from '@citadel/app-chess/client';
import { snakeClientRegistration as bundledClientRegistration2 } from '@citadel/app-snake/client';
import { chatServerRegistration as bundledServerRegistration0 } from '@citadel/app-chat/server';
import { chessServerRegistration as bundledServerRegistration1 } from '@citadel/app-chess/server';
import { snakeServerRegistration as bundledServerRegistration2 } from '@citadel/app-snake/server';

export type BundledInstalledApp = {
  descriptor: AppPackageDescriptor;
  clientRegistration: ClientAppRegistration<any>;
  serverRegistration: ServerAppRegistration<any>;
};

const bundledAppDescriptor0 = {
  appId: "chat",
  manifest: {
    appId: "chat",
    label: "Chat",
    defaultSpaceId: "general",
    persistence: "sqlite",
    version: "0.1.0"
  },
  packageName: "@citadel/app-chat",
  client: {
    subpath: "./client",
    registrationExport: "chatClientRegistration"
  },
  server: {
    subpath: "./server",
    registrationExport: "chatServerRegistration"
  }
} satisfies AppPackageDescriptor;

const bundledAppDescriptor1 = {
  appId: "chess",
  manifest: {
    appId: "chess",
    label: "Chess",
    defaultSpaceId: "general",
    persistence: "sqlite",
    version: "0.1.0"
  },
  packageName: "@citadel/app-chess",
  client: {
    subpath: "./client",
    registrationExport: "chessClientRegistration"
  },
  server: {
    subpath: "./server",
    registrationExport: "chessServerRegistration"
  }
} satisfies AppPackageDescriptor;

const bundledAppDescriptor2 = {
  appId: "snake",
  manifest: {
    appId: "snake",
    label: "Snake",
    defaultSpaceId: "general",
    persistence: "none",
    version: "0.1.0"
  },
  packageName: "@citadel/app-snake",
  client: {
    subpath: "./client",
    registrationExport: "snakeClientRegistration"
  },
  server: {
    subpath: "./server",
    registrationExport: "snakeServerRegistration"
  }
} satisfies AppPackageDescriptor;

export const bundledInstalledApps = [
  {
    descriptor: bundledAppDescriptor0,
    clientRegistration: bundledClientRegistration0,
    serverRegistration: bundledServerRegistration0
  },
  {
    descriptor: bundledAppDescriptor1,
    clientRegistration: bundledClientRegistration1,
    serverRegistration: bundledServerRegistration1
  },
  {
    descriptor: bundledAppDescriptor2,
    clientRegistration: bundledClientRegistration2,
    serverRegistration: bundledServerRegistration2
  }
] satisfies BundledInstalledApp[];

export const bundledAppDescriptorByPackageName: Record<string, AppPackageDescriptor> = {
  "@citadel/app-chat": bundledAppDescriptor0,
  "@citadel/app-chess": bundledAppDescriptor1,
  "@citadel/app-snake": bundledAppDescriptor2
};

export const bundledAppDescriptorByAppId: Record<string, AppPackageDescriptor> = {
  "chat": bundledAppDescriptor0,
  "chess": bundledAppDescriptor1,
  "snake": bundledAppDescriptor2
};

export const bundledClientRegistrationByPackageName: Record<string, ClientAppRegistration<any>> = {
  "@citadel/app-chat": bundledClientRegistration0,
  "@citadel/app-chess": bundledClientRegistration1,
  "@citadel/app-snake": bundledClientRegistration2
};

export const bundledClientRegistrationByAppId: Record<string, ClientAppRegistration<any>> = {
  "chat": bundledClientRegistration0,
  "chess": bundledClientRegistration1,
  "snake": bundledClientRegistration2
};

export const bundledServerRegistrationByPackageName: Record<string, ServerAppRegistration<any>> = {
  "@citadel/app-chat": bundledServerRegistration0,
  "@citadel/app-chess": bundledServerRegistration1,
  "@citadel/app-snake": bundledServerRegistration2
};

export const bundledServerRegistrationByAppId: Record<string, ServerAppRegistration<any>> = {
  "chat": bundledServerRegistration0,
  "chess": bundledServerRegistration1,
  "snake": bundledServerRegistration2
};
