// Generated by scripts/generate-bundled-apps.mjs. Do not edit by hand.
import type { InstalledAppCatalogEntry } from '../platform/app.js';



export const bundledInstalledApps = [

] satisfies InstalledAppCatalogEntry[];
