// Generated by scripts/generate-bundled-apps.mjs. Do not edit by hand.
import type { AppPackageDescriptor } from '@citadel/platform/app';
import { chatAppPackage as bundledAppPackage0 } from '@citadel/app-chat';
import { chessAppPackage as bundledAppPackage1 } from '@citadel/app-chess';
import { snakeAppPackage as bundledAppPackage2 } from '@citadel/app-snake';

export const bundledAppDescriptorByPackageName: Record<string, AppPackageDescriptor> = {
  '@citadel/app-chat': bundledAppPackage0,
  '@citadel/app-chess': bundledAppPackage1,
  '@citadel/app-snake': bundledAppPackage2
};
