// Generated by citadel-generate-app-metadata from package.json#citadel.

import type { AppManifest, AppPackageDescriptor } from '@citadel/platform/app';

export const generatedManifest = {
  appId: "chat",
  label: "Chat",
  defaultSpaceId: "general",
  persistence: "sqlite",
  version: "0.1.0"
} satisfies AppManifest;

export const generatedAppPackage = {
  appId: generatedManifest.appId,
  manifest: generatedManifest,
  packageName: "@citadel/app-chat",
  client: {
    subpath: "./client",
    registrationExport: "chatClientRegistration"
  },
  server: {
    subpath: "./server",
    registrationExport: "chatServerRegistration"
  }
} satisfies AppPackageDescriptor;
