// Generated by scripts/generate-local-app-metadata.mjs from package.json#citadel.

import type { AppManifest, AppPackageDescriptor } from '@citadel/platform/app';

export const generatedManifest = {
  appId: "chess",
  label: "Chess",
  defaultSpaceId: "general",
  persistence: "sqlite",
  version: "0.1.0"
} satisfies AppManifest;

export const generatedAppPackage = {
  appId: generatedManifest.appId,
  manifest: generatedManifest,
  packageName: "@citadel/app-chess",
  client: {
    subpath: "./client",
    registrationExport: "chessClientRegistration"
  },
  server: {
    subpath: "./server",
    registrationExport: "chessServerRegistration"
  }
} satisfies AppPackageDescriptor;
