import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import type { AppPackageDescriptor } from './appContract.js';

const outputFileName = 'generatedMetadata.ts';
const header = '// Generated by citadel-generate-app-metadata from package.json#citadel.\n';

type PackageJson = {
  name?: unknown;
  citadel?: unknown;
};

type CitadelMetadata = Record<string, unknown>;

type GenerateOptions = {
  check?: boolean;
  packageDirs?: string[];
};

function literal(value: string) {
  return JSON.stringify(value);
}

function readRequiredString(metadata: CitadelMetadata, key: string, packageName: string) {
  const value = metadata[key];

  if (typeof value !== 'string' || value.length === 0) {
    throw new Error(`App package ${packageName} citadel.${key} must be a non-empty string`);
  }

  return value;
}

function readPersistence(metadata: CitadelMetadata, packageName: string) {
  const value = readRequiredString(metadata, 'persistence', packageName);

  if (value !== 'none' && value !== 'sqlite') {
    throw new Error(`App package ${packageName} citadel.persistence must be "none" or "sqlite"`);
  }

  return value;
}

function readRegistrationMetadata(
  metadata: CitadelMetadata,
  environment: 'client',
  packageName: string
): AppPackageDescriptor['client'];
function readRegistrationMetadata(
  metadata: CitadelMetadata,
  environment: 'server',
  packageName: string
): AppPackageDescriptor['server'];
function readRegistrationMetadata(
  metadata: CitadelMetadata,
  environment: 'client' | 'server',
  packageName: string
) {
  const registration = metadata[environment];

  if (!registration || typeof registration !== 'object' || Array.isArray(registration)) {
    throw new Error(`App package ${packageName} citadel.${environment} must declare registration metadata`);
  }

  const registrationMetadata = registration as CitadelMetadata;
  const subpath = readRequiredString(registrationMetadata, 'subpath', packageName);

  if (subpath !== './client' && subpath !== './server') {
    throw new Error(`App package ${packageName} citadel.${environment}.subpath must be "./client" or "./server"`);
  }

  const registrationExport = readRequiredString(registrationMetadata, 'registrationExport', packageName);

  if (environment === 'client') {
    return {
      subpath: './client',
      registrationExport
    };
  }

  return {
    subpath: './server',
    registrationExport
  };
}

export function parseAppPackageMetadata(packageName: string, packageJson: PackageJson): AppPackageDescriptor {
  if (packageJson.name !== packageName) {
    throw new Error(`App package mismatch: expected ${packageName}, package.json declares ${String(packageJson.name)}`);
  }

  const metadata = packageJson.citadel;

  if (!metadata || typeof metadata !== 'object' || Array.isArray(metadata)) {
    throw new Error(`App package ${packageName} must declare citadel metadata`);
  }

  const citadelMetadata = metadata as CitadelMetadata;
  const appId = readRequiredString(citadelMetadata, 'appId', packageName);

  return {
    appId,
    manifest: {
      appId,
      label: readRequiredString(citadelMetadata, 'label', packageName),
      defaultSpaceId: readRequiredString(citadelMetadata, 'defaultSpaceId', packageName),
      persistence: readPersistence(citadelMetadata, packageName),
      version: readRequiredString(citadelMetadata, 'version', packageName)
    },
    packageName,
    client: readRegistrationMetadata(citadelMetadata, 'client', packageName),
    server: readRegistrationMetadata(citadelMetadata, 'server', packageName)
  };
}

export function generateAppMetadataSource(packageDir: string) {
  const packageJson = JSON.parse(readFileSync(join(packageDir, 'package.json'), 'utf8')) as PackageJson;
  const packageName = packageJson.name;

  if (typeof packageName !== 'string' || packageName.length === 0) {
    throw new Error(`App package at ${packageDir} must declare package.json name`);
  }

  const descriptor = parseAppPackageMetadata(packageName, packageJson);

  return [
    header,
    "import type { AppManifest, AppPackageDescriptor } from '@citadel/platform/app';",
    '',
    'export const generatedManifest = {',
    `  appId: ${literal(descriptor.manifest.appId)},`,
    `  label: ${literal(descriptor.manifest.label)},`,
    `  defaultSpaceId: ${literal(descriptor.manifest.defaultSpaceId)},`,
    `  persistence: ${literal(descriptor.manifest.persistence)},`,
    `  version: ${literal(descriptor.manifest.version)}`,
    '} satisfies AppManifest;',
    '',
    'export const generatedAppPackage = {',
    '  appId: generatedManifest.appId,',
    '  manifest: generatedManifest,',
    `  packageName: ${literal(descriptor.packageName)},`,
    '  client: {',
    `    subpath: ${literal(descriptor.client.subpath)},`,
    `    registrationExport: ${literal(descriptor.client.registrationExport)}`,
    '  },',
    '  server: {',
    `    subpath: ${literal(descriptor.server.subpath)},`,
    `    registrationExport: ${literal(descriptor.server.registrationExport)}`,
    '  }',
    '} satisfies AppPackageDescriptor;',
    ''
  ].join('\n');
}

export function generateAppMetadata(options: GenerateOptions = {}) {
  const packageDirs = options.packageDirs?.length ? options.packageDirs : [process.cwd()];
  const staleFiles: string[] = [];

  for (const packageDirInput of packageDirs) {
    const packageDir = resolve(packageDirInput);
    const outputPath = join(packageDir, 'src', outputFileName);
    const expectedSource = generateAppMetadataSource(packageDir);
    const currentSource = existsSync(outputPath) ? readFileSync(outputPath, 'utf8') : undefined;

    if (options.check) {
      if (currentSource !== expectedSource) {
        staleFiles.push(outputPath);
      }

      continue;
    }

    writeFileSync(outputPath, expectedSource);
  }

  if (staleFiles.length > 0) {
    throw new Error([
      'Generated app metadata is stale. Run citadel-generate-app-metadata.',
      ...staleFiles.map((filePath) => `- ${filePath}`)
    ].join('\n'));
  }
}
